# Generated by Django 4.2.9 on 2024-07-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_payment_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_lesson',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.PositiveIntegerField(default=1000, verbose_name='Сумма платежа'),
        ),
    ]
