# Generated by Django 4.2.9 on 2024-07-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Сессия'),
        ),
    ]
